USE T7_Project;

SELECT C.*, V.* FROM T7_CUSTOMER C
INNER JOIN T7_CLAIM CL
ON C.T7_Cust_Id = CL.T7_Cust_Id
INNER JOIN T7_VEHICLE V
ON CL.T7_VEHICLE_Id = V.T7_VEHICLE_Id
INNER JOIN T7_INCIDENT I
ON I.T7_VEHICLE_Id = V.T7_VEHICLE_Id
WHERE CL.T7_Claim_Status = 'Pending';